---
- hosts: all
  # become: yes
  # become_user: xxxxx
  # remote_user: xxxxx
  gather_facts: no

  tasks:

  - name: Created new build directory
    file: path=<path>/ps-node.{{ build_no }} state=directory
  - name: Downloading the build tat
    get_url: url=<path>/ps-node.{{ build_no }}.tar.gz dest=/tmp
  - name: Untar the build
    unarchive: src=/tmp/ps-node.{{ build_no }}.tar.gz dest=<path>/ps-node.{{ build_no }} remote_src=yes
  - name: Webstopping
    command: webstop
  - name: creating softllink
    command: rm -rf <path>
  - name: creating new live link
    command: ln -s <path>/ps-node.{{ build_no }} live
  - name: Webstarting
    command: webstart
    register: command_result
    failed_when: "'Error' in command_result.stderr"
